### PR TITLE
Added spanish translations

### PR DESCRIPTION
**Pull request by miguelcanosantana**
Using the Android Studio Locale Editor.

### CODE REVIEW

**Review by CraZyLegenD — CHANGES_REQUESTED** [review]
the folder should be named values-es
not values-es-rES
After that we're ready to go.

**Comment by miguelcanosantana** [comment]
Changed xml from values-es-rES to values-es.

**Review by CraZyLegenD — CHANGES_REQUESTED** [review]
I'm sorry for this but since you're adding Spanish we have to have another string for that too

`<string name="spanish">Espanol</string>`
or whatever the translation is in your language, haha.

**Comment by miguelcanosantana** [comment]
Do you add it or should I do it? And if I need to do it where :P

**Comment by CraZyLegenD** [comment]
> Do you add it or should I do it? And if I need to do it where :P

Check the latest commit, I've added it.

**Review by CraZyLegenD — APPROVED** [review]

**Comment by miguelcanosantana** [comment]
Thanks for letting me collab, I'm still a bit clumsy hahaha, that was my first pull request.

**Comment by CraZyLegenD** [comment]
> Thanks for letting me collab, I'm still a bit clumsy hahaha, that was my first pull request.

No probs, I don't see the `<string name="spanish">Spanish</string>` translation in your strings 
did you maybe forget to add it before I merged it?

**Comment by miguelcanosantana** [comment]
Isnt't it in the last line of https://github.com/CraZyLegenD/Vigilante/blob/master/app/src/main/res/values-es/strings.xml

**Comment by CraZyLegenD** [comment]
> Isnt't it in the last line of https://github.com/CraZyLegenD/Vigilante/blob/master/app/src/main/res/values-es/strings.xml

I just added it, thank you nevertheless i hope it's correct translation.

**Pull request merged**
